[package]
name = "wasmtimer"
edition = "2021"
description = "Abstraction over std::time::Instant and futures-timer that works on WASM"
version = "0.0.1"
authors = ["WhizSid <whizsid@aol.com>"]
license = "MIT"
repository = "https://github.com/whizsid/wasmtimer-rs"

[dependencies]
futures = "0.3"
parking_lot = "0.12"
pin-utils = "0.1.0"
js-sys = "0.3"
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
web-sys = { version = "0.3", features = ["Performance", "Window"] }

[dev-dependencies]
async-std = "1.0"
